name: MenuService
main: com.m0pt0pmatt.menuservice.MenuServicePlugin
version: 0.6
author: m0pt0pmatt
permissions:
  menuservice.*:
    description: Have access to all MenuService commands
    children:
      menuservice.open: true
      menuservice.close: true
      menuservice.bind: true
      menuservice.unbind: true
      menuservice.load: true
      menuservice.reload: true
      menuservice.save: true
      menuservice.help: true
      menuservice.list: true
      menuservice.edit: true
  menuservice.open:
    description: Opens a Menu for a player
    default: false
  menuservice.close:
    description: Closes the Menu for a player
    default: false
  menuservice.list:
    description: List all currently loaded Menus
    default: false
  menuservice.bind:
    description: Binds a Menu to an item or a material
    default: false
  menuservice.unbind:
    description: Unbinds Menus from an item or a material
    default: false
  menuservice.load:
    description: loads a Menu from file
    default: false
  menuservice.reload:
    description: reloads a Menu from file
    default: false
  menuservice.unload:
    description: unloads a Menu from MenuService
    default: false
  menuservice.save:
    description: saves a Menu to file
    default: false
  menuservice.edit:
    description: Opens the Menu Manager
    default: false
  menuservice.help:
    description: Get the help menu for MenuService
    default: true
commands: 
  menuservice: